import Link from 'next/link';
import { Page } from '@/components/Site';
import StructuredData from '@/components/StructuredData';
import { pageMetadata, breadcrumbSchema } from '@/lib/seo';
import { packages, site, whatsappUrl } from '@/lib/site';
import { money } from '@/lib/calculator';
const path='/house-construction-chennai';
const title='Architect-Led House Construction in Chennai';
const description='Plan your Chennai home with Bind Builds. Compare construction packages from ₹2,399/sq.ft, understand approvals and discuss architect-led design and construction.';
export const metadata=pageMetadata(title,description,path);
export default function ChennaiConstruction(){return <Page kicker="BIND BUILDS / HOUSE CONSTRUCTION IN CHENNAI" title="House construction in Chennai."><article className="guidePage"><nav className="guideBreadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span>House construction in Chennai</span></nav><header className="guideIntro"><span className="productEyebrow">Architecture. Engineering. Construction.</span><h2>One coordinated team.<br/><span>Your Chennai home.</span></h2><p>Bind Builds connects architectural design, engineering coordination and construction. Begin with the life your home needs to support, then define the area, specifications and agreement that make the budget meaningful.</p><div className="guideActions"><Link className="cta primary" href="/start-a-project">Discuss my home ↗</Link><Link className="productTextLink" href="/cost-calculator">Calculate my budget →</Link></div></header>
<section className="guideSection"><span className="productEyebrow">Construction cost in Chennai</span><h2>Know the rate.<br/><span>Understand the scope.</span></h2><p>Our three published starting packages use an agreed construction-area basis. The same plot can support different budgets because floors, specifications, foundations and excluded work change the scope.</p><div className="serviceRates">{packages.map(item=><article key={item.key}><h3>{item.name}</h3><strong>{money(item.rate)}<small> / sq.ft*</small></strong><p>{item.description}</p><Link href={'/packages#'+item.key}>View {item.name} specification →</Link></article>)}</div><div className="constructionExample"><div><span className="productEyebrow">Illustrative base-cost comparison</span><h3>2,000 sq.ft.<br/>Three specifications.</h3><p>Same calculated area × each package rate.</p></div><dl>{packages.map(item=><div key={item.key}><dt>{item.name}</dt><dd>{money(2000*item.rate)}</dd></div>)}</dl></div><p className="guideSmall">*Starting base construction rates, not a final quotation. The illustration excludes land, taxes, approvals, site-specific work, external works and fit-out outside the agreed specification. Area measurement and every inclusion need confirmation in your proposal.</p><div className="guideActions"><Link href="/cost-calculator" className="productTextLink">Change the area and build your estimate →</Link><Link href="/construction-cost-chennai" className="productTextLink">Read the detailed 2026 cost guide →</Link></div></section>
<section className="guideSection"><span className="productEyebrow">What an architect-led process changes</span><h2>The decisions connect.</h2><div className="guideCards three">{[['Design around your family','Plan privacy, circulation, light, ventilation and future needs before committing to the building layout.'],['Coordinate the drawings','Connect architectural, structural and services decisions so the team works from an agreed direction.'],['Make the scope visible','Compare material allowances, site supervision, documentation, exclusions and the change process—not only the headline rate.']].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div><p>Studio Bind Architects began in 2019. Bind Builds is the construction chapter launched in 2026, led by Ar. Parthiban Moorthy. Our portfolio explains our role and project status so you can review relevant experience.</p><div className="guideActions"><a className="productTextLink" href={site.portfolio} target="_blank" rel="noopener noreferrer">Explore design and site experience ↗</a><Link className="productTextLink" href="/about">Meet the practice →</Link></div></section>
<section className="guideSection"><span className="productEyebrow">Plan for the actual Chennai site</span><h2>Your location.<br/><span>Your design decisions.</span></h2><div className="documentGrid">{[['01','Rain and drainage','Discuss site levels, neighbouring runoff, roof falls and the proposed drainage connection.'],['02','Heat and privacy','Consider orientation, shading, cross-ventilation and the neighbouring buildings.'],['03','Access and ground conditions','Review road access, material movement and soil investigation before finalising foundation assumptions.'],['04','Approvals and future floors','Check the applicable rules and structural needs before committing to a floor count or later extension.']].map(([n,h,p])=><article key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div><p>Share your Chennai locality—such as Pallikaranai, Porur, Valasaravakkam, Adyar or Anna Nagar—and the site context. We confirm project fit, visit arrangements and the scope for your exact location in the first conversation.</p><div className="guideActions"><Link className="productTextLink" href="/building-plan-approval-chennai">Read the Chennai building approval guide →</Link><Link className="productTextLink" href="/turnkey-house-construction-chennai">Explore turnkey house construction →</Link><Link className="productTextLink" href="/service-areas-chennai">Check construction service areas →</Link></div></section>
<section className="guideSection"><span className="productEyebrow">Choose a useful next step</span><h2>Where are you now?</h2><div className="guideCards three"><article><h3>I’m exploring a budget.</h3><p>Try the area-based calculator. It shows the base, your allowances and the assumptions behind the total.</p><Link href="/cost-calculator">Calculate my estimate →</Link></article><article><h3>I have a plot.</h3><p>Gather your site details and prepare for a conversation about design and the approval route.</p><Link href="/building-plan-approval-chennai#prepare">Prepare my site checklist →</Link></article><article><h3>I’m ready to discuss.</h3><p>Share your requirements. Project-specific design begins after the scope, fee and advance are agreed.</p><Link href="/start-a-project">Prepare my project brief →</Link></article></div></section>
<section className="guideSection guideFaq"><h2>A few answers before we talk.</h2>{[
['How do I compare construction companies in Chennai?','Compare the same drawings, area measurement, material allowances, supervision scope, payment milestones and exclusions. Ask to see relevant work and understand the company’s role in it.'],['Can you work with my existing drawings?','We can discuss your architectural, structural and services drawings and their approval status. Any additional design or coordination work needs an agreed scope before a construction proposal.'],['Are approvals included in the square-foot rate?','Building-plan approval is excluded from the published packages. Discuss professional fees, authority charges and any related investigations separately.'],['Can you give me a free floor plan?','Project-specific design is a paid professional engagement. The first conversation helps us understand your site, priorities and the appropriate next step.'],['How long will my house take to build?','The programme depends on the agreed area, complexity, site access, decisions, permissions and construction sequence. We discuss a project-specific programme after the scope is clear.']
].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section className="guideClosing"><h2>Let’s think it through.</h2><p>Bring your location, requirements and a starting budget.</p><div className="guideActions"><Link className="cta primary" href="/start-a-project">Plan my home ↗</Link><a className="productTextLink" href={whatsappUrl('Hello Bind Builds, I would like to discuss architect-led house construction in Chennai.')} target="_blank" rel="noopener noreferrer">Talk on WhatsApp ↗</a></div><p className="guideSmall">Chennai · English & Tamil · Studio discussions and site visits by appointment</p></section></article><StructuredData data={[breadcrumbSchema('House construction in Chennai',path),{'@context':'https://schema.org','@type':'Service',name:title,description,serviceType:'Architect-led house construction',url:site.url+path,provider:{'@type':'Organization','@id':site.url+'/#organization',name:site.name,url:site.url},areaServed:{'@type':'City',name:'Chennai'}}]}/></Page>;}
