import Link from 'next/link';
import { pageMetadata, organizationSchema, localBusinessSchema, founderPersonSchema } from '@/lib/seo';
import StructuredData from '@/components/StructuredData';
export const metadata=pageMetadata('Architect-Led Construction Company in Chennai','Bind Builds brings design, engineering and construction together for your Chennai home. Compare packages, calculate your budget and prepare for building approvals.','/');
import { Nav, Footer } from '@/components/Site';
import { HomeHero, HomeBudget, DetailIcon } from '@/components/HomeExperience';
import { BuildAssurance, BrandEcosystem } from '@/components/BuildAssurance';
import { packages, site, whatsappUrl } from '@/lib/site';
const highlights = [
 {kind:'plan' as const,eyebrow:'Architecture first',title:<>A home that starts<br/>with you.</>,copy:'Your family. Your routines. Your light and air. The plan comes together before the site work begins.',detail:'Floor plans, facade design and coordinated drawings give the team a shared direction. Project-specific design starts after an agreed paid engagement.',metric:'Design first',label:'Across all three packages'},
 {kind:'connect' as const,eyebrow:'One coordinated team',title:<>Fewer gaps.<br/>A clearer journey.</>,copy:'Architecture, engineering and construction connected from the first conversation to handover.',detail:'The process connects your design decisions, engineering inputs, construction scope and site execution. One coordinated point of contact keeps the conversation together.',metric:'01',label:'Coordinated point of contact'},
 {kind:'scope' as const,eyebrow:'Clarity in your budget',title:<>Know what goes<br/>into your home.</>,copy:'Compare the materials, allowances and exclusions behind every square-foot rate.',detail:'Each package has ten specification sections, including the exclusion schedule. Compare the same area and scope, then confirm every inclusion in your proposal.',metric:'10',label:'Specification sections per package'},
 {kind:'progress' as const,eyebrow:'Progress you can see',title:<>The site moves.<br/>You stay in the loop.</>,copy:'Progress documentation and site coordination make the work easier to follow.',detail:'Daily progress photos or documentation are listed across our packages. Engineer supervision, project-manager visits and architect support follow the selected specification and project agreement.',metric:'Daily',label:'Progress documentation in package scope'},
];
export default function Home(){return <><Nav/><main id="main-content" className="premiumHome"><HomeHero/><StructuredData data={[organizationSchema,localBusinessSchema,founderPersonSchema,{'@context':'https://schema.org','@type':'WebSite',name:'Bind Builds',url:site.url,'@id':site.url+'/#website',publisher:{'@id':site.url+'/#organization'}}]}/>
 <section className="proofRail" aria-label="Bind Builds at a glance"><div><strong>2019</strong><span>The design practice began</span></div><div><strong>01</strong><span>Coordinated team</span></div><div><strong>{String(packages.length).padStart(2,'0')}</strong><span>Clear package choices</span></div><div><strong>₹{packages[0].rate.toLocaleString('en-IN')}<small>/sq.ft*</small></strong><span>Essential starting rate</span></div></section><p className="proofFootnote">*Base construction starting rate. Final scope, taxes and exclusions are confirmed in your proposal.</p>
 <section className="productSection highlightsSection" id="highlights"><div className="productSectionHeader reveal"><span className="productEyebrow">The Bind Builds difference</span><h2>The thinking<br/><span>makes the difference.</span></h2><p>Good architecture connects the life you imagine<br className="desktopBreak"/> with the details that make it work.</p></div><div className="highlightGrid">{highlights.map((item,index)=><article className="highlightCard reveal" key={item.kind} style={{'--delay':`${index%2*80}ms`} as React.CSSProperties}><div className="highlightCardTop"><span className="productEyebrow">{item.eyebrow}</span><span className="highlightIndex">0{index+1}</span></div><h3>{item.title}</h3><p>{item.copy}</p><DetailIcon kind={item.kind}/><div className="highlightMetric"><strong>{item.metric}</strong><span>{item.label}</span></div><details><summary><span className="highlightSummaryLabel">Look closer</span><b aria-hidden="true">+</b></summary><p>{item.detail}</p></details></article>)}</div></section>
 <section className="productSection designStatement"><span className="productEyebrow reveal">A simple idea. A better starting point.</span><h2 className="reveal">The plan is<br/><span>part of the build.</span></h2><p className="reveal">So we connect the architect, the engineer and the site.<br className="desktopBreak"/> Your home benefits from the whole picture.</p><div className="connectedProcess reveal" aria-label="Design, coordinate, build"><div><span>01</span><strong>Design.</strong><small>Your life, in a plan.</small></div><i aria-hidden="true"/><div><span>02</span><strong>Coordinate.</strong><small>Every detail aligned.</small></div><i aria-hidden="true"/><div><span>03</span><strong>Build.</strong><small>One agreed direction.</small></div></div><Link href="/process" className="productTextLink">See how it comes together <span aria-hidden="true">→</span></Link></section>
 <section className="productSection specificationSection" id="specifications"><div className="productSectionHeader reveal"><span className="productEyebrow">Your specification. Your budget.</span><h2>Make room for<br/><span>the right numbers.</span></h2><p>Move the area. Compare the packages.<br/>See what a different specification means for your budget.</p></div><HomeBudget/></section>
 <BuildAssurance/>
 <section className="productSection studioStatement"><div className="studioYears reveal"><span>2019</span><i aria-hidden="true"/><span>2026</span><p>Studio Bind Architects → Bind Builds</p></div><div className="reveal"><span className="productEyebrow">The practice behind the build</span><h2>Architectural thinking.<br/><span>From day one.</span></h2><p>Led by Ar. Parthiban Moorthy, Bind Builds brings the design and site experience of Studio Bind Architects into a coordinated construction service.</p><div className="studioLinks"><Link className="productTextLink" href="/about">Meet the practice →</Link><a className="productTextLink" href={site.studio} target="_blank" rel="noopener noreferrer">Explore the design studio ↗</a></div></div></section>
 <section className="productSection confidenceSection" id="confidence-before-commit"><div className="productSectionHeader reveal"><span className="productEyebrow">Confidence before you commit</span><h2>Proof before<br/><span>promise.</span></h2><p>A construction decision should not depend on a logo, a sales pitch or a headline square-foot rate. Here is what we make clear so you can assess us properly.</p></div><div className="confidenceGrid">
  <article className="confidenceCard reveal"><span className="confidenceNo">01</span><div><h3>One practice. Two chapters.</h3><p>Studio Bind Architects began in 2019. Bind Builds launched in 2026 as the construction chapter. We identify the role behind each example instead of presenting design or interior work as a completed Bind Builds turnkey project.</p><Link href="/about" className="productTextLink">Understand the practice →</Link></div></article>
  <article className="confidenceCard reveal"><span className="confidenceNo">02</span><div><h3>Evidence, with context.</h3><p>Where relevant material is available, drawings, photographs, progress records or site examples are explained with the project stage and our role. An ongoing site is not presented as a completed handover.</p><Link href="/project-evidence" className="productTextLink">Review project evidence →</Link></div></article>
  <article className="confidenceCard reveal"><span className="confidenceNo">03</span><div><h3>Scope before construction.</h3><p>Your proposal should make the area basis, package specification, exclusions and payment stages visible. Project-specific design, engineering and construction documents then follow the agreed engagement and approvals.</p><Link href="/packages" className="productTextLink">Compare the written scope →</Link></div></article>
  <article className="confidenceCard reveal"><span className="confidenceNo">04</span><div><h3>Site visits, when they are relevant.</h3><p>A relevant project visit can be discussed when owner permission, scheduling and site safety allow it. If a suitable visit is not available, we say so rather than substituting an unrelated example.</p><Link href="/faq" className="productTextLink">Read the confidence FAQs →</Link></div></article>
 </div><div className="confidenceActions reveal"><Link href="/start-a-project" className="cta primary">Start with my project brief ↗</Link><Link href="/process" className="productTextLink">See the process before you decide →</Link></div></section>
 <section className="productSection productFaq"><div className="productSectionHeader reveal"><span className="productEyebrow">Building in Chennai</span><h2>Good questions.<br/><span>Clear answers.</span></h2></div><div className="faqPreview">{[
 ['What is included in the square-foot rate?','Each package has a specification and exclusion schedule. Review materials, allowances, area measurement, supervision, taxes and external works together before comparing totals.'],
 ['Should I have a floor plan before we talk?','You can begin with your location, plot dimensions, the spaces you need and an approximate budget. We discuss the right next step and the paid design engagement before developing your project.'],
 ['Will the calculator give me a final quote?','It gives you a planning estimate using our published base rates and any allowances you enter. Your site, design, area and agreed scope determine the project-specific proposal.'],
 ['Is Studio Bind’s design experience the same as Bind Builds’ construction track record?','No. Studio Bind Architects began in 2019; Bind Builds launched as the construction chapter in 2026. We separate design, interiors, site coordination, ongoing construction and completed construction so you can assess the role relevant to your home.'],
 ].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}<Link href="/faq" className="productTextLink">Explore the Chennai construction FAQs →</Link></div></section>
 <section className="productSection homeGuidesSection"><div className="productSectionHeader"><span className="productEyebrow">Planning construction in Chennai</span><h2>A clearer start.<br/><span>A useful next step.</span></h2><p>Useful guides for the decisions people usually make before a construction proposal.</p></div><div className="homeGuideLinks homeGuideEditorial"><Link href="/construction-company-chennai"><span className="productEyebrow">Compare before you commit</span><h3>Construction company<br/>in Chennai.</h3><p>See what to compare across scope, design, engineering, site supervision, exclusions and project evidence.</p><strong>Compare the right things →</strong></Link><Link href="/construction-cost-chennai"><span className="productEyebrow">2026 / Cost guide</span><h3>Construction cost<br/>in Chennai.</h3><p>See package rates, sample budgets, cost drivers and what to compare between quotations.</p><strong>Understand the numbers →</strong></Link><Link href="/building-plan-approval-chennai"><span className="productEyebrow">Your site / Your permissions</span><h3>Before the build.<br/>Know the approval route.</h3><p>Documents, authority roles, cost considerations and a checklist for your first conversation.</p><strong>Prepare for building plan approval →</strong></Link><Link href="/turnkey-house-construction-chennai"><span className="productEyebrow">One coordinated team</span><h3>Turnkey house<br/>construction in Chennai.</h3><p>Understand how design, engineering, scope and site execution connect through one engagement.</p><strong>Explore the turnkey model →</strong></Link><Link href="/service-areas-chennai"><span className="productEyebrow">Where we work</span><h3>Priority construction<br/>areas + corridors.</h3><p>West Chennai, Anna Nagar, OMR, ECR and selected Coimbatore projects—qualified by the actual site and scope.</p><strong>Explore service areas →</strong></Link><Link href="/demolition-rebuild-house-chennai"><span className="productEyebrow">Existing house / New home</span><h3>Demolition + rebuild<br/>in Chennai.</h3><p>Plan the existing structure, demolition scope, approvals and new construction as one coordinated project.</p><strong>Plan a rebuild →</strong></Link></div></section>
 <section className="productSection finalInvitation"><span className="productEyebrow">Your home starts here</span><h2>Let’s think it through.<br/><span>Together.</span></h2><p>Bring your ideas. We’ll help you find the next step.</p><div className="productHeroActions"><Link href="/start-a-project" className="cta primary">Plan my home ↗</Link><a href={whatsappUrl()} className="productTextLink" target="_blank" rel="noopener noreferrer">Talk on WhatsApp ↗</a></div><small>Chennai · Selected Coimbatore projects · English or Tamil</small></section>
 <BrandEcosystem/>
 </main><Footer/></>;}
