'use client';
import { useState } from 'react';
import Link from 'next/link';
import { readinessItems } from '@/lib/approval-guide';
import { whatsappUrl } from '@/lib/site';
export default function ApprovalReadiness(){
 const [ready,setReady]=useState<string[]>([]);
 const [location,setLocation]=useState('');
 const [dimensions,setDimensions]=useState('');
 const [project,setProject]=useState('New home');
 const remaining=readinessItems.filter(item=>!ready.includes(item.id));
 const notes=['Chennai approval-planning enquiry','Project: '+project,'Site locality: '+(location.trim()||'To be discussed'),'Plot dimensions: '+(dimensions.trim()||'To be confirmed'),'Information gathered: '+(readinessItems.filter(item=>ready.includes(item.id)).map(item=>item.label).join('; ')||'Starting from the beginning'),'Still to gather or clarify: '+(remaining.map(item=>item.label).join('; ')||'All six topics noted; professional verification still required'),'Please discuss the approval route, required records, and the scope and fee for a site-specific review. This checklist does not assess eligibility or grant approval.'].join('\n');
 const enquiry='/start-a-project?'+new URLSearchParams({location:location.trim(),notes});
 return <section className="approvalReadiness" id="prepare"><div className="readinessIntro"><span className="productEyebrow">A useful first conversation</span><h2>Know your next step.</h2><p>Tick the information you have gathered. We’ll carry your checklist into your enquiry so the conversation starts with your site.</p><div className="readinessCount" aria-live="polite"><strong>{ready.length}<small> / 6</small></strong><span>topics prepared for discussion</span></div><progress value={ready.length} max={6} aria-label="Topics prepared for discussion"/><p className="guideSmall">This is a preparation checklist, not an approval or eligibility assessment. Your selections stay in this page until you choose to share them.</p></div><div className="readinessFields"><div className="fields"><label>Site locality <span>(optional)</span><input autoComplete="address-level2" maxLength={120} placeholder="For example, Pallikaranai" value={location} onChange={event=>setLocation(event.target.value)}/></label><div className="fieldPair"><label>Plot dimensions <span>(optional)</span><input maxLength={80} placeholder="For example, 27 × 46 ft" value={dimensions} onChange={event=>setDimensions(event.target.value)}/></label><label>Project<select value={project} onChange={event=>setProject(event.target.value)}><option>New home</option><option>Demolition and rebuild</option><option>Rental / multi-family home</option><option>Other development</option></select></label></div></div><fieldset><legend>What have you gathered?</legend>{readinessItems.map(item=><label className="readinessItem" key={item.id}><input type="checkbox" checked={ready.includes(item.id)} onChange={event=>setReady(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><span><strong>{item.label}</strong><small>{item.hint}</small></span></label>)}</fieldset><div className="readinessNext" aria-live="polite"><strong>{ready.length===6?'Your discussion checklist is ready.':'Start with what you know.'}</strong><p>{remaining.length?`${remaining.length} ${remaining.length===1?'topic remains':'topics remain'} to gather or clarify. You can still talk to us now.`:'The next step is a site-specific review, with its scope and professional fee agreed first.'}</p></div><div className="guideActions"><Link className="cta primary" href={enquiry}>Discuss my site ↗</Link><a className="productTextLink" href={whatsappUrl('Hello Bind Builds,\n\n'+notes)} target="_blank" rel="noopener noreferrer">Open WhatsApp draft ↗</a></div><p className="guideSmall">Share a general location only. Keep deeds and identity documents for a secure, direct exchange with the team. WhatsApp sends your message only after you press Send.</p></div></section>;
}
