'use client';
import {useState} from 'react';
export type PackageCategory={no:string;title:string;essential:string[];elevate:string[];signature:string[]};
type Tier='essential'|'elevate'|'signature';
const tiers:{key:Tier;name:string;price:string;label:string}[]=[{key:'essential',name:'ESSENTIAL',price:'₹2,399',label:'01'},{key:'elevate',name:'ELEVATE',price:'₹2,649',label:'02'},{key:'signature',name:'SIGNATURE',price:'₹3,199',label:'03'}];
export default function PackageComparison({categories}:{categories:PackageCategory[]}){const [open,setOpen]=useState<Record<string,number>>({});return <><div className="simplePackageGrid">{tiers.map(t=><article className={`simplePackageCard ${t.key==='elevate'?'featured':''}`} key={t.key}><header className="simplePackageHead"><span className="eyebrow">{t.label} — BIND BUILDS</span><h2>{t.name}</h2><div className="simplePrice"><strong>{t.price}</strong><span>/ SQ.FT*</span></div><p>WHAT’S INCLUDED</p></header><div className="simplePackageCategories">{categories.map((c,i)=>{const isOpen=open[t.key]===i;return <div className={`simpleCategory ${isOpen?'open':''}`} key={c.title}><button onClick={()=>setOpen(v=>({...v,[t.key]:isOpen?-1:i}))} aria-expanded={isOpen}><span>{c.title}</span><b>{isOpen?'−':'+'}</b></button><div className="simpleCategoryPanel"><div><ul>{c[t.key].map(x=><li key={x}>{x}</li>)}</ul></div></div></div>})}</div></article>)}</div><style jsx global>{`
.simplePackageGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;margin-top:8vw;background:#111;border:1px solid #111}.simplePackageCard{background:#f7f4ee;padding:3.2vw}.simplePackageCard.featured{background:#fff}.simplePackageHead{min-height:280px;padding-bottom:2.5vw}.simplePackageHead h2{font-size:clamp(36px,4vw,68px);font-weight:500;letter-spacing:-.055em;margin:2vw 0 2.5vw}.simplePrice{display:flex;align-items:flex-end;gap:10px}.simplePrice strong{font-size:clamp(42px,5vw,76px);line-height:.9;letter-spacing:-.055em}.simplePrice span{font-size:12px;opacity:.5;padding-bottom:6px}.simplePackageHead p{margin:22px 0 0;font-size:9px;letter-spacing:.2em;opacity:.45}.simplePackageCategories{border-top:1px solid #1113}.simpleCategory{border-bottom:1px solid #1113}.simpleCategory button{width:100%;min-height:72px;border:0;background:transparent;color:inherit;display:grid;grid-template-columns:1fr 28px;gap:12px;align-items:center;text-align:left;padding:0;cursor:pointer}.simpleCategory button span{font-size:15px;font-weight:600}.simpleCategory button b{font-size:25px;font-weight:300;text-align:right;color:#135de5}.simpleCategoryPanel{display:grid;grid-template-rows:0fr;transition:grid-template-rows .45s cubic-bezier(.16,1,.3,1)}.simpleCategory.open .simpleCategoryPanel{grid-template-rows:1fr}.simpleCategoryPanel>div{overflow:hidden}.simpleCategory ul{list-style:none;margin:0;padding:0 0 24px}.simpleCategory li{font-size:12px;line-height:1.5;padding:8px 0 8px 17px;position:relative;border-top:1px solid #11112}.simpleCategory li:before{content:'↗';position:absolute;left:0;opacity:.4}.flow>div{grid-template-columns:72px minmax(0,1fr) 42px!important;column-gap:18px}.flow>div>small{font-size:12px;line-height:1;opacity:.55}.flowLabel{min-width:0}.flowArrow{text-align:right}
@media(max-width:900px){.simplePackageGrid{grid-template-columns:1fr;margin-top:14vw;background:transparent;border:0;gap:18px}.simplePackageCard{border:1px solid #111;padding:8vw 6vw}.simplePackageHead{min-height:0;padding-bottom:9vw}.simplePackageHead h2{font-size:11vw;margin:5vw 0}.simplePrice strong{font-size:13vw}.simplePrice span{font-size:11px}.simplePackageHead p{margin-top:6vw}.simpleCategory button{min-height:68px}.simpleCategory button span{font-size:16px}.simpleCategory li{font-size:13px}.flow>div{grid-template-columns:34px minmax(0,1fr) 28px!important;column-gap:12px}.flow>div>small{font-size:9px}}
`}</style></>}
