'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { site, whatsappUrl } from '@/lib/site';
type Brief = {type:string;location:string;stage:string;area:string;budget:string;timeline:string;notes:string;name:string;phone:string;email:string;package:string};
const initial:Brief={type:'New home',location:'',stage:'Land purchased',area:'',budget:'Not decided yet',timeline:'Exploring options',notes:'',name:'',phone:'',email:'',package:''};
export default function ProjectForm(){
 const [step,setStep]=useState(0);
 const [form,setForm]=useState<Brief>(initial);
 const [prepared,setPrepared]=useState(false);
 const [copyStatus,setCopyStatus]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const tier=params.get('package');const area=params.get('area');setForm(value=>({...value,package:['Essential','Elevate','Signature'].includes(tier||'')?tier!:'',area:area&&/^\d{1,6}$/.test(area)?area:''}));},[]);
 useEffect(()=>{if(step>0||prepared)heading.current?.focus();},[step,prepared]);
 const update=(key:keyof Brief,value:string)=>setForm(current=>({...current,[key]:value}));
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(step<2)setStep(step+1);else setPrepared(true);};
 const brief=['Hello Bind Builds, I would like to discuss my project.','', 'Name: '+form.name,'Phone: '+form.phone,form.email?'Email: '+form.email:'','Project: '+form.type,'Location: '+form.location,'Stage: '+form.stage,'Approx. built-up area: '+(form.area?form.area+' sq.ft':'To be discussed'),'Budget: '+form.budget,'Preferred start: '+form.timeline,form.package?'Package interest: '+form.package:'',form.notes?'Requirements: '+form.notes:'','','Enquiry from the Bind Builds website.'].filter(Boolean).join('\n');
 const copy=async()=>{try{await navigator.clipboard.writeText(brief);setCopyStatus('Brief copied. Paste it into your message.');}catch{setCopyStatus('Copy is unavailable. Select and copy the brief below.');}};
 if(prepared)return <div className="projectForm preparedBrief"><span className="eyebrow">One last step</span><h2 ref={heading} tabIndex={-1}>Your brief is ready to send.</h2><p>Choose WhatsApp or email. Review the draft in your app and press Send to reach our team.</p><pre className="briefPreview">{brief}</pre><div className="sendActions"><a className="cta primary" href={whatsappUrl(brief)} target="_blank" rel="noopener noreferrer">Open WhatsApp with my brief ↗</a><a className="cta" href={'mailto:'+site.email+'?subject='+encodeURIComponent('Bind Builds project enquiry — '+form.location)+'&body='+encodeURIComponent(brief)}>Open email draft ↗</a></div><div className="formActions"><button type="button" className="textButton" onClick={()=>setPrepared(false)}>← Edit details</button><button type="button" className="textButton" onClick={copy}>Copy brief</button></div><p role="status">{copyStatus}</p><p className="smallPrint">Your enquiry is sent only when you press Send in WhatsApp or email. Need help? <a href={'tel:'+site.telephone}>Call {site.phone}</a>.</p></div>;
 return <div className="enquiryLayout"><aside className="enquiryAside"><span className="eyebrow">A good place to begin</span><h2>A few details.<br />A useful conversation.</h2><p>Tell us what you are planning. You can review your brief before sending it directly to our team.</p><ol><li>Discuss your site and priorities</li><li>Understand the scope and next step</li><li>Begin design after an agreed engagement</li></ol><p className="smallPrint">English or Tamil · No commitment to proceed</p></aside><div className="projectForm"><ol className="formSteps" aria-label="Project brief progress">{['Your project','Your priorities','Your details'].map((label,index)=><li key={label} aria-current={step===index?'step':undefined}><span>{index+1}</span>{label}</li>)}</ol><form onSubmit={submit}><h2 ref={heading} tabIndex={-1}>{['What are you planning?','What matters to you?','How can we reach you?'][step]}</h2>
 {step===0&&<div className="fields"><label>Project type<select value={form.type} onChange={e=>update('type',e.target.value)}>{['New home','Demolition & rebuild','Rental / multi-family building','Commercial','Healthcare','Retail / hospitality','Interiors','Other'].map(value=><option key={value}>{value}</option>)}</select></label><label>Site location <span>(required)</span><input required maxLength={120} autoComplete="address-level2" value={form.location} onChange={e=>update('location',e.target.value)} placeholder="For example, Pallikaranai, Chennai" /></label><label>Current stage<select value={form.stage} onChange={e=>update('stage',e.target.value)}>{['Land purchased','Looking for a plot','Design in progress','Approved drawings ready','Existing building to renovate / rebuild'].map(value=><option key={value}>{value}</option>)}</select></label></div>}
 {step===1&&<div className="fields"><label>Approximate total built-up area <span>(sq.ft · optional)</span><input type="number" inputMode="numeric" min="1" max="999999" step="1" value={form.area} onChange={e=>update('area',e.target.value)} placeholder="Combined area of all floors" /></label><div className="fieldPair"><label>Construction budget<select value={form.budget} onChange={e=>update('budget',e.target.value)}>{['Not decided yet','Under ₹25 lakh','₹25–50 lakh','₹50 lakh–₹1 crore','₹1–2 crore','Above ₹2 crore'].map(value=><option key={value}>{value}</option>)}</select></label><label>Preferred start<select value={form.timeline} onChange={e=>update('timeline',e.target.value)}>{['Exploring options','Within 3 months','3–6 months','6–12 months','After 12 months'].map(value=><option key={value}>{value}</option>)}</select></label></div><label>Your priorities <span>(optional)</span><textarea maxLength={800} rows={3} value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Bedrooms, parents’ needs, rental units, Vastu…" /></label>{form.package&&<p className="selectionNote">Package interest: {form.package}</p>}</div>}
 {step===2&&<div className="fields"><label>Your name <span>(required)</span><input required minLength={2} maxLength={80} autoComplete="name" value={form.name} onChange={e=>update('name',e.target.value)} /></label><label>Phone number <span>(with country code if outside India)</span><input required type="tel" inputMode="tel" autoComplete="tel" maxLength={22} pattern="[+0-9() -]{10,22}" title="Enter a phone number with 10–15 digits, including country code if outside India." value={form.phone} onChange={e=>update('phone',e.target.value)} onInput={e=>{const input=e.currentTarget;const count=input.value.replace(/\D/g,'').length;input.setCustomValidity(count>=10&&count<=15?'':'Please enter 10–15 digits.');}} /></label><label>Email <span>(optional)</span><input type="email" autoComplete="email" maxLength={150} value={form.email} onChange={e=>update('email',e.target.value)} /></label><p className="smallPrint">Your details stay in this page until you choose a messaging app. We use the brief you send to respond to your project enquiry. <Link href="/privacy">Privacy details</Link>.</p></div>}
 <div className="formActions">{step>0?<button className="textButton" type="button" onClick={()=>setStep(step-1)}>← Back</button>:<span className="smallPrint">Step {step+1} of 3</span>}<button className="cta primary" type="submit">{step===2?'Review my brief':'Continue'} →</button></div></form></div></div>;
}
