import type { Metadata } from 'next';
import { site } from './site';
export function pageMetadata(title:string,description:string,path:string):Metadata {
 return {title:path==='/'?{absolute:title+' | '+site.name}:title,description,alternates:{canonical:path},robots:{index:true,follow:true},openGraph:{type:'website',locale:'en_IN',siteName:site.name,title:title+' | '+site.name,description,url:site.url+path,images:[{url:'/opengraph-image',width:1200,height:630,alt:title+' | '+site.name}]},twitter:{card:'summary_large_image',title:title+' | '+site.name,description,images:['/opengraph-image']}};
}
export function breadcrumbSchema(name:string,path:string){return {'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site.url},{'@type':'ListItem',position:2,name,item:site.url+path}]};}
export const organizationSchema={'@context':'https://schema.org','@type':'Organization','@id':site.url+'/#organization',name:site.name,url:site.url,logo:{'@type':'ImageObject',url:site.url+'/bind-builds-logo.svg'},image:site.url+'/opengraph-image',description:'Architect-led construction in Chennai, connecting design, engineering and site execution.',telephone:site.telephone,email:site.email,address:{'@type':'PostalAddress',...site.address},sameAs:[site.instagram],hasMap:site.maps,areaServed:{'@type':'City',name:'Chennai'},founder:{'@id':site.url+'/#founder'},contactPoint:{'@type':'ContactPoint',telephone:site.telephone,email:site.email,contactType:'project enquiries',areaServed:'IN',availableLanguage:['English','Tamil']}};
export const localBusinessSchema={'@context':'https://schema.org','@type':'HomeAndConstructionBusiness','@id':site.url+'/#localbusiness',name:site.name,url:site.url,logo:site.url+'/bind-builds-logo.svg',image:site.url+'/opengraph-image',description:'Architect-led home construction company serving Chennai and nearby urban areas.',telephone:site.telephone,email:site.email,priceRange:'₹₹₹',address:{'@type':'PostalAddress',...site.address},areaServed:{'@type':'City',name:'Chennai'},sameAs:[site.instagram],hasMap:site.maps,founder:{'@id':site.url+'/#founder'},parentOrganization:{'@id':site.url+'/#organization'}};

export const founderPersonSchema={'@context':'https://schema.org','@type':'Person','@id':site.url+'/#founder',name:'Parthiban Moorthy',jobTitle:'Founder & Principal Architect',url:site.url+'/about',worksFor:{'@id':site.url+'/#organization'},knowsAbout:['Architecture','Residential construction','Interior design','Project coordination','Chennai home construction']};
