import type { Metadata } from 'next';
import { pageMetadata } from '@/lib/seo';
import Link from 'next/link';
import { notFound, permanentRedirect } from 'next/navigation';
import { Page } from '@/components/Site';
import ProjectForm from '@/components/ProjectForm';
import { site, whatsappUrl } from '@/lib/site';
const titles:Record<string,string>={about:'Our Story & Founder',contact:'Contact the Chennai Studio','start-a-project':'Discuss Your Construction Project',privacy:'Enquiry Privacy'};
export function generateStaticParams(){return Object.keys(titles).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const descriptions:Record<string,string>={about:'Meet Ar. Parthiban Moorthy and the practice behind Bind Builds: Studio Bind Architects since 2019, and architect-led construction in Chennai since 2026.',contact:'Contact Bind Builds in Chennai to discuss architect-led home construction, site requirements and budgets. Conversations in English and Tamil by appointment.','start-a-project':'Prepare your Chennai construction project brief. Share your location, requirements and budget, then review your enquiry before sending it to Bind Builds.',privacy:'How Bind Builds handles website project enquiries, messaging drafts and personal information.'};return pageMetadata(titles[slug]||'Page not found',descriptions[slug]||'Bind Builds — Chennai construction.','/'+slug);}
export default async function Slug({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;
 if(slug==='projects')permanentRedirect(site.portfolio);
 if(slug==='start-a-project')return <Page kicker="YOUR PROJECT / LET’S BEGIN" title="A home begins with a conversation."><section className="section enquirySection"><ProjectForm /></section></Page>;
 if(slug==='about')return <Page kicker="OUR STORY / SINCE 2019" title="Designed with purpose. Built with care.">
  <section className="section"><div className="aboutIntroGrid"><h2 className="lead">The thinking behind<br /><span className="muted">the building.</span></h2><div><p>A home is a long-term decision. The plan, light, ventilation, materials and details will shape how you live in it every day.</p><p>Bind Builds brings architectural thinking into the construction process, connecting design, engineering and execution through one coordinated team.</p></div></div><div className="benefitGrid">{[['01','People before plans.','We start with how your family lives, what your site offers and what your budget needs to achieve.'],['02','Decisions before site work.','Design, engineering and specifications are coordinated so the team can build from an agreed direction.'],['03','Value beyond handover.','Comfort, usability, maintenance and the details you live with matter as much as the first impression.']].map(([no,title,text])=><article className="benefit reveal" key={no}><span className="index">{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section dark"><span className="eyebrow">One practice / Two chapters</span><h2 className="lead">Design experience.<br /><span className="muted">A construction purpose.</span></h2><div className="timeline"><article className="reveal"><time>2019</time><h3>Studio Bind Architects</h3><p>Architecture and interior design practice. Experience across homes, healthcare, hospitality, retail, offices and commercial spaces.</p><a className="textLink" href={site.studio} target="_blank" rel="noopener noreferrer">Explore the design studio ↗</a></article><article className="reveal"><time>2026</time><h3>Bind Builds</h3><p>The next chapter: architect-led construction. Bringing planning, coordination and execution together for clients who want a clearer building journey.</p><Link className="textLink" href="/process">Explore the building process ↗</Link></article></div></section>
  <section className="section aboutTransparency"><div className="aboutTransparencyHead"><span className="eyebrow">How to assess us</span><h2 className="lead">The role should be<br/><span className="muted">as clear as the result.</span></h2><p>We do not treat every project image as the same kind of evidence. When you review our work, ask what our role was and what stage the project had reached.</p></div><div className="transparencyGrid">{[
   ['01','Design work','Architecture or interior design should be assessed as design experience — not automatically as completed turnkey construction.'],
   ['02','Site coordination','Site supervision or coordination should be identified for the specific responsibility and stage involved.'],
   ['03','Ongoing construction','An active site can show organisation, drawings and work in progress, but it is not a completed handover.'],
   ['04','Construction scope','Your own proposal and agreement should define the specification, exclusions, responsibilities, milestones and change process before execution.']
  ].map(([no,title,copy])=><article key={no}><span>{no}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="aboutTransparencyLinks"><Link className="textLink" href="/faq">Review confidence-before-you-commit FAQs →</Link><Link className="textLink" href="/process">See the pre-construction process →</Link></div></section>
  <section className="section founderSection"><div><span className="eyebrow">Founder & Principal Architect</span><p className="founderName">Ar. Parthiban Moorthy</p><span className="smallPrint">Studio Bind Architects · Bind Builds</span></div><div className="reveal"><h2 className="lead">One point of view.<br /><span className="muted">The whole picture.</span></h2><p className="bigCopy">A home should work beautifully for the people who live in it.</p><p>Parthiban’s practice connects architecture, interiors, site coordination and the decisions that turn a drawing into a usable space. Bind Builds extends that approach into a coordinated construction service.</p><div className="serviceTags">{['Architecture','Engineering coordination','Interiors','Site execution','Project communication'].map(item=><span key={item}>{item}</span>)}</div><Link className="cta primary" href="/start-a-project">Discuss your project ↗</Link></div></section></Page>;
 if(slug==='contact')return <Page kicker="CHENNAI / ENGLISH & TAMIL" title="Let’s talk about your project."><section className="section contactGrid"><div><h2 className="lead">Start with your site.<br /><span className="muted">We’ll take it from there.</span></h2><p className="bigCopy">A new home, a rebuild or a space for your business. Share what you are planning and where you would like to build.</p><p>Chennai, Tamil Nadu<br />Studio discussions and site visits by appointment.</p><a className="cta primary" href="#contact-enquiry">Fill project enquiry ↘</a></div><div className="contactOptions"><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer"><span>Send a message</span><strong>Chat on WhatsApp ↗</strong></a><a href={'tel:'+site.telephone}><span>Call the studio</span><strong>{site.phone}</strong></a><a href={'mailto:'+site.email}><span>Email your requirements</span><strong>{site.email}</strong></a><Link href="/faq"><span>Still exploring?</span><strong>Chennai construction FAQs ↗</strong></Link></div></section><section className="section enquirySection" id="contact-enquiry"><ProjectForm source="Website – Contact Form" /></section></Page>;
 if(slug==='privacy')return <Page kicker="YOUR PROJECT ENQUIRY" title="Your details. A clear purpose."><section className="section"><div className="prose"><p>This page explains how website project enquiries and estimate-download signups are handled.</p><h2>Project enquiries</h2><p>When you submit the project enquiry form, the details you provide are sent to Bind Builds for follow-up. They are recorded in the Bind Builds website lead sheet and an email notification is sent to the team.</p><h2>Estimate PDF downloads</h2><p>You can view and present a planning estimate without signing up. To download the estimate PDF, we ask for your name, phone number and email address. Those details and the associated estimate summary are sent to Bind Builds before the PDF is released.</p><h2>WhatsApp and email</h2><p>If you choose to continue through WhatsApp or your email app, your project brief is passed to that service as a draft for you to review and send. Those services process information under their own policies.</p><h2>What to include</h2><p>Share your contact details and a general project location. Please do not include property deeds, identity documents, banking details or other sensitive documents in these forms.</p><h2>Questions or deletion requests</h2><p>Contact <a className="textLink" href={'mailto:'+site.email}>{site.email}</a> if you would like to ask about or request deletion of an enquiry you have sent.</p><h2>Website analytics</h2><p>Google Analytics may be used to understand page visits, scroll depth, calculator and enquiry-funnel use, campaign/referrer attribution and website conversion events such as project enquiries, calls, WhatsApp clicks and estimate downloads. Analytics events do not intentionally include the contact details entered into our forms.</p><h2>Website delivery</h2><p>The website is hosted on Vercel. Google services are used for analytics and the interim website lead sheet and notification workflow. Hosting and external providers may process technical request information needed to deliver these services.</p></div></section></Page>;
 notFound();
}
