import type { Metadata } from 'next';
import Link from 'next/link';
import {Page} from '@/components/Site';
export const metadata:Metadata={title:'From Planning to Construction',description:'Understand the Bind Builds process from your brief and paid design engagement through plans, approvals, engineering and site commencement.',alternates:{canonical:'/process'}};
const milestones=[
{no:'01',title:'DISCOVERY MEETING + REQUIREMENT FREEZE',body:'We begin with a discovery meeting with the users to understand the family, lifestyle, priorities, site context, expectations and project needs.',output:'Understanding the users + finalized project requirements / design brief.'},
{no:'02',title:'SCHEMATIC FLOOR PLANNING',body:'Initial floor plan concepts are prepared from the finalized requirements, site conditions and lifestyle needs.',output:'Shortlisted 1–2 schematic floor plan options for discussion.'},
{no:'03',title:'DESIGN DEVELOPMENT',body:'The shortlisted plan is refined through design discussion and feedback. The architectural character and facade are developed in parallel.',output:'Revised floor plan • Facade concept • Exterior 3D design presentation.'},
{no:'04',title:'DESIGN FREEZE + CLIENT SIGN-OFF',body:'The floor plan, spatial planning and facade direction are finalized and formally frozen.',output:'Client-signed confirmation of the finalized floor plan + 3D facade elevation.'},
{no:'05',title:'FINAL AREA + CONSTRUCTION AGREEMENT',body:'The finalized design establishes the confirmed construction area and agreed project scope.',output:'Construction Agreement based on built-up area, specifications, commercial terms and construction scope.'},
{no:'06',title:'SOIL INVESTIGATION',body:'Soil testing establishes bearing capacity, soil strata, ground conditions and foundation recommendations.',output:'Soil investigation report as a key input for structural design.'},
{no:'07',title:'PLANNING / BUILDING APPROVAL DRAWINGS',body:'The finalized architectural design is converted into the required approval drawing set for submission to the concerned authority / consultant.',output:'Approval drawing and documentation set prepared for submission.'},
{no:'08',title:'STRUCTURAL DESIGN',body:'Once the soil report and finalized architectural drawings are available, the design package is issued to the Structural Consultant.',output:'Foundation • Columns • Beams • Slabs • Staircase • Structural details.'},
{no:'09',title:'CONSTRUCTION GFC DRAWING SET',body:'Architecture, structure and building services are coordinated into Good For Construction drawings for execution.',output:'Architectural • Structural • MEP • Approved facade / 3D design references.'},
{no:'10',title:'BHOOMI POOJA + CONSTRUCTION COMMENCEMENT',body:'With applicable approvals received, the site ready, and structural inputs and commencement drawings in place, the project formally transitions from pre-construction to site execution.',output:'Project ready for site mobilisation and construction commencement.'}
];
export default function Process(){return <Page kicker="OUR PROCESS / PLAN · BUILD · DELIVER" title="Clear steps. Confident decisions."><section className="section"><div className="sectionHeading"><span className="eyebrow">Before construction</span><h2 className="lead">From your first idea.<br/><span className="muted">To a plan we can build.</span></h2><p>We explain the next decision and what it produces. Project-specific design begins after the design scope, fee and advance are agreed.</p></div><div className="milestones">{milestones.map((m,i)=><details className="milestone" key={m.no} open={i===0}><summary><small>{m.no}</small><strong>{m.title}</strong><span aria-hidden="true">+</span></summary><div className="milestoneContent"><p>{m.body}</p><div className="milestoneOutput"><span className="eyebrow">What you receive</span><strong>{m.output}</strong></div></div></details>)}</div><p className="processNote">The sequence is coordinated for your site. Feasibility and approval requirements are reviewed early; work starts only after applicable approvals and the drawings needed for that stage are in place. Existing-building demolition, if needed, is separately scoped and scheduled.</p></section><section className="section dark"><div className="grid"><span className="eyebrow">During construction</span><div><h2 className="lead">One coordinated team.<br/><span className="muted">Stage by stage.</span></h2><div className="flow">{['Site mobilisation & setting out','Foundation & structure','Services & finishes','Quality reviews & documentation','Snag review & handover'].map((text,i)=><div key={text}><small>0{i+1}</small><span>{text}</span><span aria-hidden="true">↓</span></div>)}</div><p className="bigCopy">The project agreement defines the scope, payment milestones, supervision and reporting arrangements. Design changes are reviewed for their cost and time impact before execution.</p><Link className="cta" href="/start-a-project">Discuss your project ↗</Link></div></div></section></Page>;}