import Link from 'next/link';import {Page} from '@/components/Site';
const milestones=[
{no:'01',title:'DISCOVERY MEETING + REQUIREMENT FREEZE',body:'We begin with a discovery meeting with the users to understand the family, lifestyle, priorities, site context, expectations and project needs.',output:'Understanding the users + finalized project requirements / design brief.'},
{no:'02',title:'SCHEMATIC FLOOR PLANNING',body:'Initial floor plan concepts are prepared from the finalized requirements, site conditions and lifestyle needs.',output:'Shortlisted 1–2 schematic floor plan options for discussion.'},
{no:'03',title:'DESIGN DEVELOPMENT',body:'The shortlisted plan is refined through design discussion and feedback. The architectural character and facade are developed in parallel.',output:'Revised floor plan • Facade concept • Exterior 3D design presentation.'},
{no:'04',title:'DESIGN FREEZE + CLIENT SIGN-OFF',body:'The floor plan, spatial planning and facade direction are finalized and formally frozen.',output:'Client-signed confirmation of the finalized floor plan + 3D facade elevation.'},
{no:'05',title:'FINAL AREA + CONSTRUCTION AGREEMENT',body:'The finalized design establishes the confirmed construction area and agreed project scope.',output:'Construction Agreement based on built-up area, specifications, commercial terms and construction scope.'},
{no:'06',title:'SOIL INVESTIGATION',body:'Soil testing establishes bearing capacity, soil strata, ground conditions and foundation recommendations.',output:'Soil investigation report as a key input for structural design.'},
{no:'07',title:'PLANNING / BUILDING APPROVAL DRAWINGS',body:'The finalized architectural design is converted into the required approval drawing set for submission to the concerned authority / consultant.',output:'Approval drawing and documentation set prepared for submission.'},
{no:'08',title:'STRUCTURAL DESIGN',body:'Once the soil report and finalized architectural drawings are available, the design package is issued to the Structural Consultant.',output:'Foundation • Columns • Beams • Slabs • Staircase • Structural details.'},
{no:'09',title:'CONSTRUCTION GFC DRAWING SET',body:'Architecture, structure and building services are coordinated into Good For Construction drawings for execution.',output:'Architectural • Structural • MEP • Approved facade / 3D design references.'},
{no:'10',title:'BHOOMI POOJA + CONSTRUCTION COMMENCEMENT',body:'With the required planning, structural inputs and commencement drawings in place, the project formally transitions from pre-construction to site execution.',output:'Project ready for site mobilisation and construction commencement.'}
];
export default function Process(){return <Page kicker="THE BIND BUILDS PROCESS" title="PLAN FIRST. BUILD WITH CLARITY."><section className="section"><div className="grid"><span className="eyebrow">PRE-CONSTRUCTION · 01—10</span><div><h2 className="lead">FROM DISCOVERY<br/>TO BHOOMI POOJA.</h2><p className="bigCopy">A clear sequence that aligns the users, design, commercial scope, approvals, structure and construction information before execution begins.</p></div></div><div style={{marginTop:'10vw',borderTop:'1px solid #111'}}>{milestones.map(m=><article key={m.no} style={{display:'grid',gridTemplateColumns:'clamp(48px,7vw,110px) minmax(0,1fr)',gap:'clamp(18px,4vw,70px)',padding:'clamp(34px,5vw,80px) 0',borderBottom:'1px solid #111'}}><div style={{fontSize:'clamp(30px,4vw,64px)',letterSpacing:'-.05em'}}>{m.no}</div><div><span className="eyebrow">MILESTONE {m.no}</span><h2 style={{fontSize:'clamp(32px,5vw,78px)',lineHeight:.94,letterSpacing:'-.055em',margin:'18px 0 28px'}}>{m.title}</h2><p style={{fontSize:'clamp(16px,1.5vw,22px)',lineHeight:1.55,maxWidth:'820px'}}>{m.body}</p><div style={{marginTop:'32px',padding:'22px 0',borderTop:'1px solid #1113',display:'grid',gridTemplateColumns:'110px 1fr',gap:'20px'}}><span className="eyebrow">KEY OUTPUT</span><strong style={{fontSize:'clamp(15px,1.3vw,19px)',lineHeight:1.5,fontWeight:500}}>{m.output}</strong></div></div></article>)}</div></section><section className="section dark"><div className="grid"><span className="eyebrow">AFTER MILESTONE 10</span><div><h2 className="lead">READY TO START<br/>ON SITE.</h2><div className="flow">{['Site mobilisation','Setting out','Excavation','Foundation','Superstructure'].map((x,i)=><div key={x}><small>{String(i+1).padStart(2,'0')}</small><span>{x}</span><span>↓</span></div>)}</div><p className="bigCopy">Construction begins with the required information frozen for the stage being executed. Remaining detailed GFC packages are released through a controlled stage-wise drawing schedule.</p><Link className="cta" href="/start-a-project" style={{marginTop:'5vw'}}>START A PROJECT ↗</Link></div></div></section></Page>}
