import Link from 'next/link';
import { Page } from '@/components/Site';
import ApprovalReadiness from '@/components/ApprovalReadiness';
import ApprovalFeeGuide from '@/components/ApprovalFeeGuide';
import StructuredData from '@/components/StructuredData';
import { pageMetadata, breadcrumbSchema } from '@/lib/seo';
import { approvalSources as sources, approvalQuestions } from '@/lib/approval-guide';
import { site } from '@/lib/site';
const path='/building-plan-approval-chennai';
const title='Building Plan Approval in Chennai: Documents & Process';
const description='Understand Chennai building plan approval, CMDA and local-body roles, documents, fees and next steps. Prepare your site checklist with Bind Builds.';
export const metadata=pageMetadata(title,description,path);
export default function ApprovalGuide(){return <Page kicker="CHENNAI / HOMEOWNER GUIDE" title="Building plan approval in Chennai."><article className="guidePage"><nav className="guideBreadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span>Building plan approval in Chennai</span></nav><header className="guideIntro"><span className="productEyebrow">A clear starting point</span><h2>Start with your site.<br/><span>Then your permissions.</span></h2><p>Planning a new home or rebuilding an existing one? Understand the approval route, prepare the right information and keep approval costs visible before committing to construction.</p><div className="guideActions"><a className="cta primary" href="#prepare">Prepare my site checklist ↓</a><Link className="productTextLink" href="/cost-calculator">Explore construction costs →</Link></div><p className="guideSmall">By Bind Builds · Updated 19 September 2026. Fee presets are reference estimates, not a verified current tariff. General guidance; the current rules and your site determine the requirements.</p></header>
<nav className="guideJump" aria-label="On this page"><a href="#route">Approval route</a><a href="#documents">Documents</a><a href="#steps">Process</a><a href="#cost">Costs & timing</a><a href="#fee-slabs">Fee slabs</a><a href="#prepare">My checklist</a></nav>
<section className="guideSection" id="route"><span className="productEyebrow">01 / Understand the route</span><h2>Which authority?<br/><span>Which permission?</span></h2><div className="guideCards"><article><span className="guideNumber">01</span><h3>Planning permission</h3><p>Within the Chennai Metropolitan Area, CMDA regulates development and delegates some categories to local bodies. Location, use and the proposal determine the route.</p><a href={sources.cmda} target="_blank" rel="noopener noreferrer">CMDA planning guidance ↗</a></article><article><span className="guideNumber">02</span><h3>Building permit</h3><p>Confirm the local-body permit requirements alongside planning permission. GCC’s procedure covers submissions through registered architects or engineers and the issue of a building permit.</p><a href={sources.gcc} target="_blank" rel="noopener noreferrer">GCC procedure ↗</a></article></div><div className="guideNote"><strong>A Chennai postal address is not an approval category.</strong><p>Confirm the exact jurisdiction and current delegation for the plot. Outside the metropolitan area, check the applicable planning authority and local body through the state portal. Do not choose an authority from the locality name alone.</p><a href={sources.portal} target="_blank" rel="noopener noreferrer">Tamil Nadu planning portal ↗</a></div><p className="guideSmall">Have an approved layout? Still check the permissions needed for the proposed building. Land-use conformity and applicable development rules matter. <a href={sources.cmda} target="_blank" rel="noopener noreferrer">CMDA explains the basis of scrutiny ↗</a></p></section>
<section className="guideSection" id="documents"><span className="productEyebrow">02 / Gather the records</span><h2>A document checklist.<br/><span>A better starting point.</span></h2><p>Use these six groups to organise your discussion. The registered professional must confirm the current checklist, record dates, attestations and documents applicable to your case.</p><div className="documentGrid">{[
['01','Ownership','Sale deed and parent documents; lease or power-of-attorney records where applicable.'],['02','Land records','Patta / Chitta / TSLR and related revenue records.'],['03','Survey','FMB or town-survey sketch, site measurements, road access and recent site photographs.'],['04','Encumbrances','An encumbrance certificate covering the required period and recency.'],['05','Existing permissions','Available layout and building approvals; identify any existing structure.'],['06','Project drawings','Site plan, floor plans and elevations prepared by the registered professional, with declarations and clearances where required.']
].map(([n,h,p])=><article key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div><p className="guideSource">Checklist reference: <a href={sources.gcc} target="_blank" rel="noopener noreferrer">Greater Chennai Corporation — Town Planning, Annexure 1 ↗</a>. Additional records may apply; this is not a complete submission checklist.</p></section>
<section className="guideSection" id="steps"><span className="productEyebrow">03 / See the sequence</span><h2>From information.<br/><span>To a permitted plan.</span></h2><ol className="approvalSteps">{[
['Confirm','Locate the site and identify the applicable authority and route.'],['Prepare','Gather records and coordinate the required drawings with the registered professional.'],['Submit','Submit through the applicable portal and retain the application reference.'],['Respond','Address scrutiny queries, site checks and the authority’s fee demand.'],['Verify','Check the issued permission, permit and conditions before scheduling construction.']
].map(([name,copy],i)=><li key={name}><span>{String(i+1).padStart(2,'0')}</span><h3>{name}</h3><p>{copy}</p></li>)}</ol><p className="guideSource">Simplified from the <a href={sources.gcc} target="_blank" rel="noopener noreferrer">GCC application procedure ↗</a>; the sequence varies with the route and proposal.</p><details className="guideDisclosure"><summary>What about self-certification?</summary><p>Tamil Nadu has a published self-certification procedure for qualifying buildings. Ask your professional to verify current eligibility and conditions before choosing it. Confirm plot area, total built-up area, height, dwelling-unit count and building configuration, along with land use, road access and setbacks. Projects outside the scheme need the applicable scrutiny route. This page does not make an eligibility decision.</p><a href={sources.self} target="_blank" rel="noopener noreferrer">Official self-certification manual (PDF, 2024) ↗</a></details></section>
<section className="guideSection" id="cost"><span className="productEyebrow">04 / Plan the budget and time</span><h2>Three cost buckets.<br/><span>One clearer conversation.</span></h2><div className="guideCards three"><article><span className="guideNumber">01</span><h3>Authority charges</h3><p>CMDA explains that development charges depend on location, proposed use and floor area. Use the applicable official demand, not a universal online rate.</p><a href={sources.cmda} target="_blank" rel="noopener noreferrer">CMDA fee guidance ↗</a></article><article><span className="guideNumber">02</span><h3>Professional scope</h3><p>Ask what the drawing preparation, coordination, submission support and revisions cover. Agree the scope and fee before work starts.</p></article><article><span className="guideNumber">03</span><h3>Site-specific work</h3><p>Discuss surveys, investigations, demolition and any specialist inputs separately. Record what is included, excluded or still to be quoted.</p></article></div><div className="guideNote"><strong>Building-plan approval is excluded from our construction packages.</strong><p>Add an optional approval-fee allowance in the calculator. It stays separate from your construction package and does not replace the authority’s demand.</p><Link href="/packages">Review package inclusions and exclusions →</Link></div><ApprovalFeeGuide/><div className="guideTiming"><h3>When can you start?</h3><p>Separate preparation time from authority review. CMDA’s charter expects complete information and full responses to queries; published service targets should not be treated as a promise for your application. Review required permissions and their conditions before fixing commencement.</p><a href={sources.charter} target="_blank" rel="noopener noreferrer">CMDA Citizen’s Charter ↗</a></div></section>
<section className="guideSection"><h2>Check once.<br/><span>Avoid preventable queries.</span></h2><ul className="approvalChecks"><li>Match owner names, survey numbers and boundaries across the records.</li><li>Confirm layout status, land use and road access before finalising drawings.</li><li>Submit complete, readable records and signed drawings in the required format.</li><li>Keep the application reference, respond to queries and save the demand, receipts and approved plans.</li></ul><p className="guideSmall">Your professional will confirm the document periods, declarations and additional clearances for your application. Do not send identity or property documents through the public enquiry form.</p></section>
<ApprovalReadiness/>
<section className="guideSection"><span className="productEyebrow">The Bind Builds approach</span><h2>Design first.<br/><span>Coordinate before site work.</span></h2><p>We start by understanding your site, family and budget. A site-specific design or approval-coordination engagement needs an agreed professional scope and fee. We’ll clarify the registered professional’s role, submission responsibility and authority charges for your project.</p><div className="guideActions"><Link className="productTextLink" href="/process">See our pre-construction process →</Link><Link className="productTextLink" href="/house-construction-chennai">Explore house construction in Chennai →</Link></div></section>
<section className="guideSection guideFaq"><h2>Questions before you apply.</h2>{approvalQuestions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<Link className="productTextLink" href="/faq">More Chennai construction questions →</Link></section>
<footer className="guideSources"><strong>Official references</strong><p>Use current government guidance and a site-specific professional review. Official procedures can change; older explanatory pages and manuals may not reflect every amendment.</p><ul><li><a href={sources.cmda} target="_blank" rel="noopener noreferrer">CMDA planning permission</a></li><li><a href={sources.gcc} target="_blank" rel="noopener noreferrer">GCC Town Planning and document checklist</a></li><li><a href={sources.portal} target="_blank" rel="noopener noreferrer">Tamil Nadu Single Window Portal</a></li><li><a href={sources.charter} target="_blank" rel="noopener noreferrer">CMDA Citizen’s Charter</a></li></ul></footer></article><StructuredData data={[breadcrumbSchema('Building plan approval in Chennai',path),{'@context':'https://schema.org','@type':'Article',headline:title,description,mainEntityOfPage:site.url+path,datePublished:'2026-09-17',dateModified:'2026-09-19',author:{'@type':'Organization',name:site.name,url:site.url},publisher:{'@type':'Organization','@id':site.url+'/#organization',name:site.name,url:site.url},citation:Object.values(sources)}]}/></Page>;}
